"""Add parent_user_id to PPDBRegistration

Revision ID: 0a4e2427dfda
Revises: e48a2db9f769
Create Date: 2026-05-16 16:34:08.175407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4e2427dfda'
down_revision: Union[str, Sequence[str], None] = 'e48a2db9f769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ppdb_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ppdb_parent_user_id', 'users', ['parent_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ppdb_registrations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_user_id')

    # ### end Alembic commands ###
