"""fix_finance_fk_constraint

Revision ID: 1833833dccb0
Revises: cabba5b647e7
Create Date: 2026-01-27 09:43:09.321757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1833833dccb0'
down_revision: Union[str, Sequence[str], None] = 'd043e121b666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_students_scholarships", 'scholarships', ['scholarship_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint("fk_students_scholarships", type_='foreignkey')

    # ### end Alembic commands ###
