"""add_target_units_and_confidential_to_documents

Revision ID: 23f6d3982973
Revises: a51f7dc7ed5c
Create Date: 2026-09-27 20:10:21.745069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f6d3982973'
down_revision: Union[str, Sequence[str], None] = 'a51f7dc7ed5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_units', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_confidential', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('is_confidential')
        batch_op.drop_column('target_units')

    # ### end Alembic commands ###
