"""create_mutabaah_tables

Revision ID: 4b22fab96845
Revises: 8ebf0604c6f9
Create Date: 2026-05-21 09:17:49.040871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b22fab96845'
down_revision: Union[str, Sequence[str], None] = '8ebf0604c6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_mutabaah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('ibadah_data', sa.String(), nullable=True),
    sa.Column('tilawah_pages', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_mutabaah', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_mutabaah_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_mutabaah_id'), ['id'], unique=False)

    op.create_table('weekly_mutabaah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('week_start_date', sa.DateTime(), nullable=True),
    sa.Column('pekanan_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_mutabaah', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_mutabaah_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_mutabaah_week_start_date'), ['week_start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_mutabaah', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_mutabaah_week_start_date'))
        batch_op.drop_index(batch_op.f('ix_weekly_mutabaah_id'))

    op.drop_table('weekly_mutabaah')
    with op.batch_alter_table('daily_mutabaah', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_mutabaah_id'))
        batch_op.drop_index(batch_op.f('ix_daily_mutabaah_date'))

    op.drop_table('daily_mutabaah')
    # ### end Alembic commands ###
