"""add_employee_and_attendance

Revision ID: 4c85ef2894a1
Revises: 1833833dccb0
Create Date: 2026-01-31 11:20:29.563370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c85ef2894a1'
down_revision: Union[str, Sequence[str], None] = '1833833dccb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nip', sa.String(), nullable=True),
    sa.Column('nuptk', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_nip'), ['nip'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_nuptk'), ['nuptk'], unique=True)

    op.create_table('employee_attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'SICK', 'PERMIT', 'ABSENT', name='attendancestatus'), nullable=True),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_attendances_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_attendances_id'), ['id'], unique=False)

    op.create_table('student_attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'SICK', 'PERMIT', 'ABSENT', name='attendancestatus'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_attendances_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendances_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_attendances_id'))
        batch_op.drop_index(batch_op.f('ix_student_attendances_date'))

    op.drop_table('student_attendances')
    with op.batch_alter_table('employee_attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_attendances_id'))
        batch_op.drop_index(batch_op.f('ix_employee_attendances_date'))

    op.drop_table('employee_attendances')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_nuptk'))
        batch_op.drop_index(batch_op.f('ix_employees_nip'))
        batch_op.drop_index(batch_op.f('ix_employees_id'))

    op.drop_table('employees')
    # ### end Alembic commands ###
