"""add_document_number_to_documents

Revision ID: 5907059b54b4
Revises: 23f6d3982973
Create Date: 2026-09-27 20:32:36.681160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5907059b54b4'
down_revision: Union[str, Sequence[str], None] = '23f6d3982973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_number', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_document_number'), ['document_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_document_number'))
        batch_op.drop_column('document_number')

    # ### end Alembic commands ###
