"""add_tahfidz_models

Revision ID: 75f3d73b2a37
Revises: 9d67af537f93
Create Date: 2026-01-31 11:50:55.588328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f3d73b2a37'
down_revision: Union[str, Sequence[str], None] = '9d67af537f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tahfidz_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('QURAN', 'MUTUN', name='memorizationtype'), nullable=True),
    sa.Column('surah_from', sa.String(), nullable=True),
    sa.Column('surah_to', sa.String(), nullable=True),
    sa.Column('kitab_name', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('exam_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tahfidz_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tahfidz_exams_id'), ['id'], unique=False)

    op.create_table('tahfidz_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('QURAN', 'MUTUN', name='memorizationtype'), nullable=True),
    sa.Column('new_memorization', sa.String(), nullable=True),
    sa.Column('review', sa.String(), nullable=True),
    sa.Column('kitab_name', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tahfidz_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tahfidz_progress_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tahfidz_progress_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tahfidz_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tahfidz_progress_id'))
        batch_op.drop_index(batch_op.f('ix_tahfidz_progress_date'))

    op.drop_table('tahfidz_progress')
    with op.batch_alter_table('tahfidz_exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tahfidz_exams_id'))

    op.drop_table('tahfidz_exams')
    # ### end Alembic commands ###
