"""add academic calendar models

Revision ID: 8043e121b888
Revises: a1b2c3d4e5f6
Create Date: 2026-02-11 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8043e121b888'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('HOLIDAY', 'EXAM', 'EVENT', 'EFFECTIVE', name='calendar_event_type_enum'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_calendar_events_date'), 'academic_calendar_events', ['date'], unique=False)
    op.create_index(op.f('ix_academic_calendar_events_id'), 'academic_calendar_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_calendar_events_id'), table_name='academic_calendar_events')
    op.drop_index(op.f('ix_academic_calendar_events_date'), table_name='academic_calendar_events')
    op.drop_table('academic_calendar_events')
    sa.Enum(name='calendar_event_type_enum').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
