"""add_versioning_to_documents

Revision ID: a51f7dc7ed5c
Revises: afb1f8eca0cd
Create Date: 2026-09-27 17:59:17.429416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51f7dc7ed5c'
down_revision: Union[str, Sequence[str], None] = 'afb1f8eca0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('replaces_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('effective_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_documents_replaces_id', 'documents', ['replaces_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_replaces_id', type_='foreignkey')
        batch_op.drop_column('effective_date')
        batch_op.drop_column('replaces_id')
        batch_op.drop_column('version')

    # ### end Alembic commands ###
