"""expand_employee_fields

Revision ID: afb1f8eca0cd
Revises: bbc9e04d6897
Create Date: 2026-05-22 10:02:05.610370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb1f8eca0cd'
down_revision: Union[str, Sequence[str], None] = 'bbc9e04d6897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('tingkat', sa.String(), nullable=True),
    sa.Column('jurusan', sa.String(), nullable=True),
    sa.Column('institusi', sa.String(), nullable=True),
    sa.Column('tahun_lulus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('education_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_education_history_id'), ['id'], unique=False)

    op.create_table('position_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('jabatan', sa.String(), nullable=True),
    sa.Column('status_pegawai', sa.String(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('tmt_mulai', sa.DateTime(), nullable=True),
    sa.Column('tmt_selesai', sa.DateTime(), nullable=True),
    sa.Column('sk_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_history_id'), ['id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nik_kepegawaian', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nama_lengkap', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('no_ktp', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tempat_lahir', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tanggal_lahir', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('jenis_kelamin', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status_pernikahan', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('jumlah_anak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alamat', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('no_hp', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('npwp', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('no_bpjs_tk', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('no_bpjs_kes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('no_rekening', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nama_bank', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('employee_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resign_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_employees_nik_kepegawaian'), ['nik_kepegawaian'], unique=True)
        batch_op.create_foreign_key('fk_employees_unit_id_units', 'units', ['unit_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employees_unit_id_units', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employees_nik_kepegawaian'))
        batch_op.drop_column('photo_url')
        batch_op.drop_column('resign_date')
        batch_op.drop_column('unit_id')
        batch_op.drop_column('employee_type')
        batch_op.drop_column('nama_bank')
        batch_op.drop_column('no_rekening')
        batch_op.drop_column('no_bpjs_kes')
        batch_op.drop_column('no_bpjs_tk')
        batch_op.drop_column('npwp')
        batch_op.drop_column('no_hp')
        batch_op.drop_column('alamat')
        batch_op.drop_column('jumlah_anak')
        batch_op.drop_column('status_pernikahan')
        batch_op.drop_column('jenis_kelamin')
        batch_op.drop_column('tanggal_lahir')
        batch_op.drop_column('tempat_lahir')
        batch_op.drop_column('no_ktp')
        batch_op.drop_column('nama_lengkap')
        batch_op.drop_column('nik_kepegawaian')

    with op.batch_alter_table('position_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_history_id'))

    op.drop_table('position_history')
    with op.batch_alter_table('education_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_education_history_id'))

    op.drop_table('education_history')
    # ### end Alembic commands ###
