"""add testimonials and gallery models

Revision ID: b55da42cc33b
Revises: 0a5e1c6cc05d
Create Date: 2026-05-17 13:33:36.609870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55da42cc33b'
down_revision: Union[str, Sequence[str], None] = '0a5e1c6cc05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_albums_id'), ['id'], unique=False)

    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_testimonials_id'), ['id'], unique=False)

    op.create_table('gallery_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['gallery_albums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_photos_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_photos_id'))

    op.drop_table('gallery_photos')
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_testimonials_id'))

    op.drop_table('testimonials')
    with op.batch_alter_table('gallery_albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_albums_id'))

    op.drop_table('gallery_albums')
    # ### end Alembic commands ###
