"""add_ppdb_foto_and_step_tracking

Revision ID: bbc9e04d6897
Revises: 4b22fab96845
Create Date: 2026-05-22 08:18:19.373786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc9e04d6897'
down_revision: Union[str, Sequence[str], None] = '4b22fab96845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ppdb_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_foto_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_completed_step', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ppdb_registrations', schema=None) as batch_op:
        batch_op.drop_column('last_completed_step')
        batch_op.drop_column('file_foto_url')

    # ### end Alembic commands ###
