"""create_meeting_minutes_and_action_items

Revision ID: c87b60e9d36a
Revises: 5907059b54b4
Create Date: 2026-09-28 05:10:58.846923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87b60e9d36a'
down_revision: Union[str, Sequence[str], None] = '5907059b54b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_minutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_notulen', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('meeting_date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('meeting_type', sa.String(), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('decisions', sa.Text(), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('absent_members', sa.Text(), nullable=True),
    sa.Column('attachment_urls', sa.Text(), nullable=True),
    sa.Column('notulis_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['notulis_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_minutes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_minutes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_minutes_meeting_date'), ['meeting_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_minutes_nomor_notulen'), ['nomor_notulen'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_minutes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_minutes_title'), ['title'], unique=False)

    op.create_table('meeting_action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('pic_user_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_minutes.id'], ),
    sa.ForeignKeyConstraint(['pic_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_action_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_action_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_action_items_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_action_items_pic_user_id'), ['pic_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_action_items_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_action_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_action_items_status'))
        batch_op.drop_index(batch_op.f('ix_meeting_action_items_pic_user_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_action_items_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_action_items_id'))

    op.drop_table('meeting_action_items')
    with op.batch_alter_table('meeting_minutes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_minutes_title'))
        batch_op.drop_index(batch_op.f('ix_meeting_minutes_status'))
        batch_op.drop_index(batch_op.f('ix_meeting_minutes_nomor_notulen'))
        batch_op.drop_index(batch_op.f('ix_meeting_minutes_meeting_date'))
        batch_op.drop_index(batch_op.f('ix_meeting_minutes_id'))

    op.drop_table('meeting_minutes')
    # ### end Alembic commands ###
