"""add file fields to ppdb registration

Revision ID: e0d9bd201a9b
Revises: 0a4e2427dfda
Create Date: 2026-05-16 20:10:12.954410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d9bd201a9b'
down_revision: Union[str, Sequence[str], None] = '0a4e2427dfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppdb_registrations', sa.Column('file_kk_url', sa.String(), nullable=True))
    op.add_column('ppdb_registrations', sa.Column('file_akta_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppdb_registrations', 'file_akta_url')
    op.drop_column('ppdb_registrations', 'file_kk_url')
    # ### end Alembic commands ###
