"""Add PPDBRegistration model

Revision ID: e48a2db9f769
Revises: f1a2b3c4d5e6
Create Date: 2026-05-16 16:27:54.749236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e48a2db9f769'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ppdb_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('student_name', sa.String(), nullable=True),
    sa.Column('nisn', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('student_data', sa.String(), nullable=True),
    sa.Column('father_data', sa.String(), nullable=True),
    sa.Column('mother_data', sa.String(), nullable=True),
    sa.Column('guardian_data', sa.String(), nullable=True),
    sa.Column('periodic_data', sa.String(), nullable=True),
    sa.Column('achievements_data', sa.String(), nullable=True),
    sa.Column('other_data', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ppdb_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ppdb_registrations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ppdb_registrations_nisn'), ['nisn'], unique=False)
        batch_op.create_index(batch_op.f('ix_ppdb_registrations_registration_number'), ['registration_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_ppdb_registrations_student_name'), ['student_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ppdb_registrations_unit'), ['unit'], unique=False)

    op.create_table('academic_calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('HOLIDAY', 'EXAM', 'EVENT', 'EFFECTIVE', name='calendareventtype'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_calendar_events_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_calendar_events_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_calendar_events_id'))
        batch_op.drop_index(batch_op.f('ix_academic_calendar_events_date'))

    op.drop_table('academic_calendar_events')
    with op.batch_alter_table('ppdb_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ppdb_registrations_unit'))
        batch_op.drop_index(batch_op.f('ix_ppdb_registrations_student_name'))
        batch_op.drop_index(batch_op.f('ix_ppdb_registrations_registration_number'))
        batch_op.drop_index(batch_op.f('ix_ppdb_registrations_nisn'))
        batch_op.drop_index(batch_op.f('ix_ppdb_registrations_id'))

    op.drop_table('ppdb_registrations')
    # ### end Alembic commands ###
