"""add video gallery and teacher of month models

Revision ID: f293781dd775
Revises: b55da42cc33b
Create Date: 2026-05-17 13:44:42.554995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f293781dd775'
down_revision: Union[str, Sequence[str], None] = 'b55da42cc33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_of_month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('quote', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_of_month', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_of_month_id'), ['id'], unique=False)

    op.create_table('video_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_gallery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_gallery_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_gallery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_gallery_id'))

    op.drop_table('video_gallery')
    with op.batch_alter_table('teacher_of_month', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_of_month_id'))

    op.drop_table('teacher_of_month')
    # ### end Alembic commands ###
